/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TasksImport } from './routes/tasks'
import { Route as FormsImport } from './routes/forms'
import { Route as IndexImport } from './routes/index'
import { Route as FormTaskIdImport } from './routes/form/$taskId'

// Create/Update Routes

const TasksRoute = TasksImport.update({
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const FormsRoute = FormsImport.update({
  path: '/forms',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormTaskIdRoute = FormTaskIdImport.update({
  path: '/form/$taskId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/form/$taskId': {
      id: '/form/$taskId'
      path: '/form/$taskId'
      fullPath: '/form/$taskId'
      preLoaderRoute: typeof FormTaskIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  FormsRoute,
  TasksRoute,
  FormTaskIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/forms",
        "/tasks",
        "/form/$taskId"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/forms": {
      "filePath": "forms.jsx"
    },
    "/tasks": {
      "filePath": "tasks.jsx"
    },
    "/form/$taskId": {
      "filePath": "form/$taskId.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
